add usage instructions to README
shreyashankar/create-ml-app pull request #1
Opened 2020-11-23 18:02 UTC by swiftdiaries

2020-11-23 18:32 UTC, shreyashankar requested changes
You can call `make run` and it will create the venv if it hasn't already been created :)

2020-11-23 18:32 UTC, shreyashankar commented on README.md
> +    make venv
s/`make venv`/ `make run`

2020-11-23 20:22 UTC, swiftdiaries commented on README.md
> +    make venv
done 👍

2020-11-24 04:52 UTC, shreyashankar approved these changes
LGTM

2020-11-24 04:52 UTC, merged